[package]
name = "test-programs"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
wasi-http-client = { path = "../../../wasi-http-client", features = ["json"] }
serde = { version = "1.0.201", features = ["derive"] }
