name: CI
on:
  push:
    branches:
      - 'main'
      - 'release-**'
  pull_request:
jobs:
  ci:
    name: Lint and test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.78.0
        with:
          components: clippy, rustfmt
      - name: cargo fmt
        run: cargo fmt --all -- --check
      - name: cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Install wasmtime
        uses: bytecodealliance/actions/wasmtime/setup@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version: "v20.0.0"
      - name: cargo test
        run: |
          cargo install cargo-component@0.11.0
          cargo test
